# Generated by Django 5.1.1 on 2024-09-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleroom',
            name='name',
            field=models.CharField(default='default_puzzle_name', max_length=100),
            preserve_default=False,
        ),
    ]
