version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./PuzzleRoom:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=PuzzleRoom.settings
    command: python manage.py migrate && daphne -b 0.0.0.0 -p 8000 PuzzleRoom.asgi:application 