services:
  - type: web
    name: puzzleroom
    runtime: python
    rootDir: DjangoProject/PuzzleRoom
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: daphne PuzzleRoom.asgi:application
