# Generated by Django 4.2.16 on 2024-12-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sliding_puzzle', '0001_initial'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliding_puzzle.puzzleroom'),
        ),
    ]
