# Generated by Django 5.1.1 on 2024-10-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0001_initial'),
        ('sliding_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliding_puzzle.puzzleroom'),
        ),
    ]
