# Generated by Django 5.1.1 on 2025-04-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puzzles/pieces/'),
        ),
    ]
