# Generated by Django 5.1.1 on 2024-09-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_puzzle_name'),
        ('rooms', '0002_puzzleroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('original_col', models.IntegerField()),
                ('original_row', models.IntegerField()),
                ('current_col', models.IntegerField(blank=True, null=True)),
                ('current_row', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.puzzleroom')),
            ],
        ),
    ]
