# Generated by Django 5.1.1 on 2025-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JigsawPuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_piece', models.ImageField(blank=True, null=True, upload_to='')),
                ('x_position', models.IntegerField(blank=True, null=True)),
                ('y_position', models.IntegerField(blank=True, null=True)),
                ('initial_x', models.IntegerField(default=0)),
                ('initial_y', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_placed', models.BooleanField(default=False)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('placed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('edges', models.JSONField(blank=True, default=dict, null=True)),
                ('player_assignment', models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JigsawPuzzleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('puzzle_image', models.ImageField(upload_to='jigsaw_puzzles/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('versus', 'Versus'), ('collaborative', 'Collaborative')], default='collaborative', max_length=15)),
                ('room_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_ready', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.IntegerField(default=2700)),
                ('completed', models.BooleanField(default=False)),
                ('moves_taken', models.IntegerField(default=0)),
                ('completion_time', models.IntegerField(default=0)),
                ('player1_moves', models.IntegerField(default=0)),
                ('player2_moves', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.IntegerField()),
                ('moves_taken', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completion_time'],
            },
        ),
    ]
