# Generated by Django 4.2.16 on 2024-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JigsawPuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_piece', models.ImageField(upload_to='jigsaw_pieces/')),
                ('x_position', models.IntegerField(blank=True, null=True)),
                ('y_position', models.IntegerField(blank=True, null=True)),
                ('initial_x', models.IntegerField(blank=True, null=True)),
                ('initial_y', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_placed', models.BooleanField(default=False)),
                ('placed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('player_assignment', models.CharField(max_length=15, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JigsawPuzzleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('puzzle_image', models.ImageField(upload_to='jigsaw_puzzles/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('versus', 'Versus'), ('collaborative', 'Collaborative')], default='collaborative', max_length=15)),
                ('room_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_ready', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(default=600)),
            ],
        ),
    ]
