# Generated by Django 5.1.1 on 2024-10-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('versus', 'Versus')], default='solo', max_length=10),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
