# Generated by Django 4.2.16 on 2024-12-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jigsaw_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigsaw_puzzle.jigsawpuzzleroom'),
        ),
    ]
