# Generated by Django 5.1.1 on 2025-04-01 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jigsaw_puzzle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='neighbors',
            field=models.ManyToManyField(to='jigsaw_puzzle.jigsawpuzzlepiece'),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigsaw_puzzle.jigsawpuzzleroom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigsaw_puzzle.jigsawpuzzleroom'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigsaw_puzzle.jigsawpuzzleroom'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
