# Generated by Django 5.1.1 on 2025-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='image_piece',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
