# Generated by Django 4.2.16 on 2024-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0002_jigsawpuzzleroom_mode_jigsawpuzzleroom_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='mode',
            field=models.CharField(choices=[('versus', 'Versus'), ('collaborative', 'Collaborative')], default='collaborative', max_length=15),
        ),
    ]
