# Generated by Django 4.2.16 on 2024-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigsawpuzzleroom',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='turn_time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
