# Generated by Django 4.2.16 on 2024-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0003_alter_jigsawpuzzleroom_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
