# Generated by Django 4.2.16 on 2024-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0003_remove_jigsawpuzzleroom_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
