# Generated by Django 4.2.16 on 2024-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0004_alter_jigsawpuzzlepiece_x_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='x_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='y_position',
            field=models.IntegerField(),
        ),
    ]
