# Generated by Django 4.2.16 on 2024-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0004_jigsawpuzzleroom_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
