# Generated by Django 4.2.16 on 2024-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0005_jigsawpuzzleroom_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='time_limit',
            field=models.IntegerField(default=600),
        ),
    ]
