# Generated by Django 4.2.16 on 2024-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0006_alter_jigsawpuzzleroom_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigsawpuzzleroom',
            name='turn_time_limit',
        ),
    ]
