# Generated by Django 4.2.16 on 2024-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0006_remove_jigsawpuzzlepiece_x_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jigsawpuzzlepiece',
            old_name='player1_x_position',
            new_name='x_position',
        ),
        migrations.RenameField(
            model_name='jigsawpuzzlepiece',
            old_name='player1_y_position',
            new_name='y_position',
        ),
        migrations.RemoveField(
            model_name='jigsawpuzzlepiece',
            name='player2_x_position',
        ),
        migrations.RemoveField(
            model_name='jigsawpuzzlepiece',
            name='player2_y_position',
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='image_piece',
            field=models.ImageField(upload_to='jigsaw_pieces/'),
        ),
    ]
