# Generated by Django 4.2.16 on 2024-12-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0007_remove_jigsawpuzzleroom_turn_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigsawpuzzleroom',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='jigsawpuzzleroom',
            name='time_limit',
        ),
    ]
