# Generated by Django 4.2.16 on 2024-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0008_remove_jigsawpuzzleroom_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='total_duration',
            field=models.IntegerField(default=600),
        ),
    ]
