# Generated by Django 4.2.16 on 2024-11-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0008_alter_jigsawpuzzlepiece_x_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='player_role',
            field=models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='x_position',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='y_position',
            field=models.IntegerField(default=-1),
        ),
    ]
