# Generated by Django 4.2.16 on 2024-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0009_jigsawpuzzlepiece_player_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='image_piece',
            field=models.ImageField(upload_to='pieces/'),
        ),
    ]
