# Generated by Django 4.2.16 on 2024-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0010_alter_jigsawpuzzlepiece_image_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigsawpuzzlepiece',
            name='player_role',
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='image_piece',
            field=models.ImageField(upload_to='jigsaw_pieces/'),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='x_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='y_position',
            field=models.IntegerField(),
        ),
    ]
