# Generated by Django 5.1.1 on 2025-01-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='edges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
