# Generated by Django 5.1.1 on 2025-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0011_jigsawpuzzlepiece_edges'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
