# Generated by Django 4.2.16 on 2024-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0011_remove_jigsawpuzzlepiece_player_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
