# Generated by Django 4.2.16 on 2024-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0012_jigsawpuzzlepiece_is_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='placed_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
