# Generated by Django 5.1.1 on 2025-01-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0012_jigsawpuzzleroom_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='initial_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='initial_y',
            field=models.IntegerField(default=0),
        ),
    ]
