# Generated by Django 5.1.1 on 2025-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0013_alter_jigsawpuzzlepiece_initial_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='edges',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
