# Generated by Django 4.2.16 on 2024-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0013_jigsawpuzzlepiece_placed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='player_assignment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
