# Generated by Django 5.1.1 on 2025-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0014_alter_jigsawpuzzlepiece_edges'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='grid_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='grid_y',
            field=models.IntegerField(default=0),
        ),
    ]
