# Generated by Django 4.2.16 on 2024-11-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0014_jigsawpuzzlepiece_player_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='x_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='y_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
