# Generated by Django 4.2.16 on 2024-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0015_alter_jigsawpuzzlepiece_x_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='locked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
