# Generated by Django 5.1.1 on 2025-02-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0016_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='moves_taken',
            field=models.IntegerField(default=0),
        ),
    ]
