# Generated by Django 5.1.1 on 2025-02-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0017_jigsawpuzzleroom_moves_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='completion_time',
            field=models.IntegerField(default=0),
        ),
    ]
