# Generated by Django 5.1.1 on 2025-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0018_jigsawpuzzleroom_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='image_piece',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='puzzle_image',
            field=models.ImageField(blank=True, null=True, upload_to='jigsaw_puzzles/'),
        ),
    ]
