# Generated by Django 5.1.1 on 2025-03-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0019_alter_jigsawpuzzlepiece_image_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='puzzle_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
