# Generated by Django 5.1.1 on 2025-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0020_alter_jigsawpuzzleroom_puzzle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='puzzle_image',
            field=models.ImageField(upload_to='jigsaw_puzzles/'),
        ),
    ]
