# Generated by Django 5.1.1 on 2025-03-09 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0021_alter_jigsawpuzzleroom_puzzle_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jigsawpuzzlepiece',
            name='player_assignment',
            field=models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=15, null=True),
        ),
    ]
