# Generated by Django 5.1.1 on 2025-03-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0022_jigsawpuzzleroom_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player1_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jigsawpuzzleroom',
            name='player2_moves',
            field=models.IntegerField(default=0),
        ),
    ]
