# Generated by Django 5.1.1 on 2025-03-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0023_jigsawpuzzleroom_player1_moves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigsawpuzzleroom',
            name='total_duration',
            field=models.IntegerField(default=2700),
        ),
    ]
