# Generated by Django 5.1.1 on 2025-03-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw_puzzle', '0024_alter_jigsawpuzzleroom_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzlepiece',
            name='neighbors',
            field=models.ManyToManyField(to='jigsaw_puzzle.jigsawpuzzlepiece'),
        ),
    ]
