# Generated by Django 4.2.16 on 2024-12-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sliding_puzzle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliding_player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliding_player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle'),
        ),
    ]
