# Generated by Django 5.1.1 on 2024-10-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliding_puzzle', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzleroom',
            name='users',
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliding_player1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliding_player2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
