# Generated by Django 5.1.1 on 2025-03-23 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliding_puzzle', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzleroom',
            options={'ordering': ['-last_played']},
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='best_moves',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='best_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='current_move_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='games_completed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puzzleroom',
            name='total_moves_made',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('moves_taken', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_taken', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('was_best_time', models.BooleanField(default=False)),
                ('was_best_moves', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to='sliding_puzzle.puzzleroom')),
            ],
            options={
                'verbose_name_plural': 'Game histories',
                'ordering': ['-completed_at'],
            },
        ),
    ]
