# Generated by Django 5.1.1 on 2025-04-01 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsPuzzleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_image', models.ImageField(upload_to='puzzles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsPuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_piece', models.ImageField(upload_to='puzzle_pieces/')),
                ('initial_x', models.IntegerField()),
                ('initial_y', models.IntegerField()),
                ('is_placed', models.BooleanField(default=False)),
                ('correct_x', models.IntegerField(default=0)),
                ('correct_y', models.IntegerField(default=0)),
                ('is_stuck', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics_puzzle.physicspuzzleroom')),
            ],
        ),
    ]
