# Generated by Django 5.1.1 on 2025-03-11 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics_puzzle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicspuzzleroom',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='physicspuzzleroom',
            name='player2',
        ),
        migrations.AddField(
            model_name='physicspuzzlepiece',
            name='correct_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physicspuzzlepiece',
            name='correct_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physicspuzzlepiece',
            name='is_stuck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='physicspuzzlepiece',
            name='image_piece',
            field=models.ImageField(upload_to='puzzle_pieces/'),
        ),
        migrations.AlterField(
            model_name='physicspuzzlepiece',
            name='initial_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicspuzzlepiece',
            name='initial_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicspuzzleroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicspuzzleroom',
            name='player1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicspuzzleroom',
            name='puzzle_image',
            field=models.ImageField(upload_to='puzzles/'),
        ),
    ]
